<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>promise之then</title>
</head>

<body>
	<script>
		const p = new Promise((resolve, reject) => {
			setTimeout(() => {
				resolve('用户数据')
				// reject('出错了')
			}, 1000);
		})
		// 调用then方法  then方法的返回结果是promise对象，
		// 对象状态由回调函数执行结果决定
		// 1.如果回调函数中返回的结果是 非promise类型的属性，状态为成功,返回值为对象的成功值
		const result = p.then(value => {
			// 1.非promise类型的属性
			console.log(value);
			// return 123;
			// 2.promise类型对象
			//里边的状态决定上层返回状态
			// return new Promise((resolve,reject)=>{
			//     // resolve('ok')
			//     reject('error')
			// })
			// 3.抛出错误  promise状态也是失败的，抛出的值就是下面设置的
			// throw new Error('出错了')
			throw '出错了'
		}, reason => {
			console.warn(reason);
		})

		//因为有上面三种特性，所以可以链式调用
		//链式调用，能够改变回调地狱
		// p.then(value=>{

		// }).then(value=>{

		// })

		console.log(result);
	</script>
</body>

</html>